/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hdc_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f7e77e35bc86ed3f077e62231fefa850)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nrsc5/hdc_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <hdc_encoder_pydoc.h>

void bind_hdc_encoder(py::module& m)
{

    using hdc_encoder    = ::gr::nrsc5::hdc_encoder;


    py::class_<hdc_encoder, gr::block, gr::basic_block,
        std::shared_ptr<hdc_encoder>>(m, "hdc_encoder", D(hdc_encoder))

        .def(py::init(&hdc_encoder::make),
           py::arg("channels") = 2,
           py::arg("bitrate") = 64000,
           D(hdc_encoder,make)
        )
        



        ;




}








