/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(l1_fm_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9e0757746c54a36eb37e7206f1242d92)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nrsc5/l1_fm_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <l1_fm_encoder_pydoc.h>

void bind_l1_fm_encoder(py::module& m)
{

    using l1_fm_encoder    = ::gr::nrsc5::l1_fm_encoder;


    py::class_<l1_fm_encoder, gr::block, gr::basic_block,
        std::shared_ptr<l1_fm_encoder>>(m, "l1_fm_encoder", D(l1_fm_encoder))

        .def(py::init(&l1_fm_encoder::make),
           py::arg("psm"),
           py::arg("ssm") = 0,
           D(l1_fm_encoder,make)
        )
        



        ;




}








