/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(psd_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5a8cf841a3a5f026ab9f8c469bb01419)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nrsc5/psd_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <psd_encoder_pydoc.h>

void bind_psd_encoder(py::module& m)
{

    using psd_encoder    = ::gr::nrsc5::psd_encoder;


    py::class_<psd_encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<psd_encoder>>(m, "psd_encoder", D(psd_encoder))

        .def(py::init(&psd_encoder::make),
           py::arg("prog_num"),
           py::arg("title"),
           py::arg("artist"),
           D(psd_encoder,make)
        )
        



        ;




}








