/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-j2497
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_J2497_API_H
#define INCLUDED_J2497_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_j2497_EXPORTS
#define J2497_API __GR_ATTR_EXPORT
#else
#define J2497_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_J2497_API_H */
