/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ieee802_11
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_IEEE802_11_API_H
#define INCLUDED_IEEE802_11_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ieee802_11_EXPORTS
#define IEEE802_11_API __GR_ATTR_EXPORT
#else
#define IEEE802_11_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_IEEE802_11_API_H */
