/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chunks_to_symbols.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d2f4de89018fc7c7ee96d450ca48179)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/chunks_to_symbols.h>
// pydoc.h is automatically generated in the build directory
#include <chunks_to_symbols_pydoc.h>

void bind_chunks_to_symbols(py::module& m)
{

    using chunks_to_symbols    = ::gr::ieee802_11::chunks_to_symbols;


    py::class_<chunks_to_symbols, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<chunks_to_symbols>>(m, "chunks_to_symbols", D(chunks_to_symbols))

        .def(py::init(&chunks_to_symbols::make),
           D(chunks_to_symbols,make)
        )
        



        ;




}








