/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode_mac.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cace2c32f544fb653ce489c979eb4082)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/decode_mac.h>
// pydoc.h is automatically generated in the build directory
#include <decode_mac_pydoc.h>

void bind_decode_mac(py::module& m)
{

    using decode_mac    = ::gr::ieee802_11::decode_mac;


    py::class_<decode_mac, gr::block, gr::basic_block,
        std::shared_ptr<decode_mac>>(m, "decode_mac", D(decode_mac))

        .def(py::init(&decode_mac::make),
           py::arg("log") = false,
           py::arg("debug") = false,
           D(decode_mac,make)
        )
        



        ;




}








