/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(extract_csi.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e25959f49b55fd96cbc9354d42ad8c72)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/extract_csi.h>
// pydoc.h is automatically generated in the build directory
#include <extract_csi_pydoc.h>

void bind_extract_csi(py::module& m)
{

    using extract_csi    = ::gr::ieee802_11::extract_csi;


    py::class_<extract_csi, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<extract_csi>>(m, "extract_csi", D(extract_csi))

        .def(py::init(&extract_csi::make),
           D(extract_csi,make)
        )
        



        ;




}








