/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mac.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1c47a20e97ec549a0e6ec5362f06ad6f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/mac.h>
// pydoc.h is automatically generated in the build directory
#include <mac_pydoc.h>

void bind_mac(py::module& m)
{

    using mac    = ::gr::ieee802_11::mac;


    py::class_<mac, gr::block, gr::basic_block,
        std::shared_ptr<mac>>(m, "mac", D(mac))

        .def(py::init(&mac::make),
           py::arg("src_mac"),
           py::arg("dst_mac"),
           py::arg("bss_mac"),
           D(mac,make)
        )
        



        ;




}








