/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(parse_mac.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ebc81ff01bea127fd4abde631ac5f0f3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/parse_mac.h>
// pydoc.h is automatically generated in the build directory
#include <parse_mac_pydoc.h>

void bind_parse_mac(py::module& m)
{

    using parse_mac    = ::gr::ieee802_11::parse_mac;


    py::class_<parse_mac, gr::block, gr::basic_block,
        std::shared_ptr<parse_mac>>(m, "parse_mac", D(parse_mac))

        .def(py::init(&parse_mac::make),
           py::arg("log") = false,
           py::arg("debug") = false,
           D(parse_mac,make)
        )
        



        ;




}








