/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_short.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ce2bf4884eae2d4c7695586469e38b17)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/sync_short.h>
// pydoc.h is automatically generated in the build directory
#include <sync_short_pydoc.h>

void bind_sync_short(py::module& m)
{

    using sync_short    = ::gr::ieee802_11::sync_short;


    py::class_<sync_short, gr::block, gr::basic_block,
        std::shared_ptr<sync_short>>(m, "sync_short", D(sync_short))

        .def(py::init(&sync_short::make),
           py::arg("threshold"),
           py::arg("min_plateau"),
           py::arg("log") = false,
           py::arg("debug") = false,
           D(sync_short,make)
        )
        



        ;




}








