/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_long.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a0194fa153fe85f65ac2b217646c1d12)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/sync_long.h>
// pydoc.h is automatically generated in the build directory
#include <sync_long_pydoc.h>

void bind_sync_long(py::module& m)
{

    using sync_long    = ::gr::ieee802_11::sync_long;


    py::class_<sync_long, gr::block, gr::basic_block,
        std::shared_ptr<sync_long>>(m, "sync_long", D(sync_long))

        .def(py::init(&sync_long::make),
           py::arg("sync_length"),
           py::arg("log") = false,
           py::arg("debug") = false,
           D(sync_long,make)
        )
        



        ;




}








