#!/bin/bash

# Check Operating System
ubuntu18_04=$(lsb_release -d 2>&1 | grep "Ubuntu 18.04")
ubuntu20_04=$(lsb_release -d 2>&1 | grep "Ubuntu 20.04")
dragonOS_focal=$(lsb_release -d 2>&1 | grep "DragonOS Focal$")
dragonOS_focalx=$(lsb_release -d 2>&1 | grep "DragonOS FocalX")
kde_neon=$(lsb_release -d 2>&1 | grep "KDE neon")
ubuntu22_04=$(lsb_release -d 2>&1 | grep "Ubuntu 22.04")

if [[ -n "$ubuntu18_04" ]]
then
    echo "Ubuntu 18.04 detected"
fi

# Python3_maint-3.8, Ubuntu 20.04, DragonOS Focal, KDE neon
if [[ -n "$ubuntu20_04" ]] || [[ -n "$dragonOS_focal" ]] || [[ -n "$kde_neon" ]]
then
    echo "Ubuntu 20.04 variant detected"
    echo "This branch is for Ubuntu 18.04 variants only. Switch to the Python3_maint-3.8 branch and try again!"
    exit
fi

# Python3_maint-3.10, Ubuntu 22.04
if [[ -n "$ubuntu22_04" ]] || [[ -n "$dragonOS_focalx" ]]
then
    echo "Ubuntu 22.04 variant detected"
    echo "This branch is for Ubuntu 18.04 variants only. Switch to the Python3_maint-3.10 branch and try again!"
    exit
fi


python_version=$(python -V 2>&1 | grep -Po '(?<=Python )(.+)')
if [[ -z "$python_version" ]]
then
    # Ubuntu 18.04
    echo "No Python!" 
    read -p "Python2 is required to open the installer. Do you want to proceed? [y]/n: " yn1
    case $yn1 in
        # No
        [Nn]* ) exit;;
        
        # Yes/Everything Else
        * )
            sudo apt-get -y update
            sudo apt-get install -y python-setuptools python-dev build-essential     
        ;;
    esac
fi

qt4_version=$(ls /usr/lib/python2.7/dist-packages/ | grep PyQt4)
if [[ -z "$qt4_version" ]]
then
    # Ubuntu 18.04
    echo "No Qt4!"
    read -p "Qt4 is required to open the installer. Do you want to proceed? [y]/n: " yn2
    case $yn2 in
        # No
        [Nn]* ) exit;;
        
        # Yes/Everything Else
        * )
            sudo apt-get -y install python-qt4 
        ;;
    esac    
fi

get_libcanberra=$(locate libcanberra-gtk-module.so 2>&1 | grep "libcanberra-gtk-module.so")
if [[ -z "$get_libcanberra" ]]
then
    # Ubuntu 18.04
    echo "No libcanberra-gtk-module!"
    read -p "libcanberra is required to open the installer. Do you want to proceed? [y]/n: " yn3
    case $yn3 in
        # No
        [Nn]* ) exit;;
        
        # Yes/Everything Else
        * )
            sudo apt-get install -y libcanberra-gtk-module
        ;;
    esac        
fi

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
$DIR/Installer/installer
