/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pad_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7a558a15cd1883b28237a8c9f3d5419f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <foo/pad_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <pad_tagged_stream_pydoc.h>

void bind_pad_tagged_stream(py::module& m)
{

    using pad_tagged_stream    = ::gr::foo::pad_tagged_stream;


    py::class_<pad_tagged_stream, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<pad_tagged_stream>>(m, "pad_tagged_stream", D(pad_tagged_stream))

        .def(py::init(&pad_tagged_stream::make),
           py::arg("buffer_size"),
           py::arg("len_tag_name"),
           D(pad_tagged_stream,make)
        )
        



        ;




}








