/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rtt_measure.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(30ed3e91a71527c380abe7384d62fcea)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <foo/rtt_measure.h>
// pydoc.h is automatically generated in the build directory
#include <rtt_measure_pydoc.h>

void bind_rtt_measure(py::module& m)
{

    using rtt_measure    = ::gr::foo::rtt_measure;


    py::class_<rtt_measure, gr::block, gr::basic_block,
        std::shared_ptr<rtt_measure>>(m, "rtt_measure", D(rtt_measure))

        .def(py::init(&rtt_measure::make),
           py::arg("interval"),
           D(rtt_measure,make)
        )
        



        ;




}








