/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-clapper_plus
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_CLAPPER_PLUS_API_H
#define INCLUDED_CLAPPER_PLUS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_clapper_plus_EXPORTS
#define CLAPPER_PLUS_API __GR_ATTR_EXPORT
#else
#define CLAPPER_PLUS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_CLAPPER_PLUS_API_H */
