/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(freqest.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0cabc668a992580cc198efcc845e51dc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ais/freqest.h>
// pydoc.h is automatically generated in the build directory
#include <freqest_pydoc.h>

void bind_freqest(py::module& m)
{

    using freqest    = ::gr::ais::freqest;


    py::class_<freqest, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<freqest>>(m, "freqest", D(freqest))

        .def(py::init(&freqest::make),
           py::arg("sample_rate"),
           py::arg("data_rate"),
           py::arg("fftlen"),
           D(freqest,make)
        )
        



        ;




}








