Sensor Node:
     archive: ''
     attack: ''
     autorun: false
     autorun_delay_seconds: 3
     autorun_interval_seconds: 3
     enabled_disabled: enabled
     ip_address: '127.0.0.1'
     iq:
          0:
               daughterboard: ''
               ip_address: ''
               network_interface: ''
               radio_name: ''
               serial: ''
               type: ''
               uid: ''
     local_remote: local
     location: fgh
     nickname: Local Sensor Node
     notes: fdh
     pd: ''
     msg_port: '5052'
     hb_port: '5051'
     tsi: ''
     console_logging_level: 'INFO'
     file_logging_level: 'DEBUG'
