/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(paint_config.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6853f2df5fbfc8036dfcce239e2e982a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <paint/paint_config.h>
// pydoc.h is automatically generated in the build directory
#include <paint_config_pydoc.h>

void bind_paint_config(py::module& m)
{


    py::enum_<::gr::paint::paint_random_t>(m,"paint_random_t")
        .value("INTERNAL", ::gr::paint::INTERNAL) // 0
        .value("EXTERNAL", ::gr::paint::EXTERNAL) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::paint::paint_random_t>();
    py::enum_<::gr::paint::paint_equalization_t>(m,"paint_equalization_t")
        .value("EQUALIZATION_OFF", ::gr::paint::EQUALIZATION_OFF) // 0
        .value("EQUALIZATION_ON", ::gr::paint::EQUALIZATION_ON) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::paint::paint_equalization_t>();



}








