/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(paint_bc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c4a81272683bd6a0b50cadaed93b5e45)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <paint/paint_bc.h>
// pydoc.h is automatically generated in the build directory
#include <paint_bc_pydoc.h>

void bind_paint_bc(py::module& m)
{

    using paint_bc    = ::gr::paint::paint_bc;


    py::class_<paint_bc, gr::block, gr::basic_block,
        std::shared_ptr<paint_bc>>(m, "paint_bc", D(paint_bc))

        .def(py::init(&paint_bc::make),
           py::arg("width"),
           py::arg("repeats"),
           py::arg("equalization"),
           py::arg("randomsrc"),
           py::arg("inputs"),
           D(paint_bc,make)
        )
        



        ;




}








