/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-garage_door
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_GARAGE_DOOR_API_H
#define INCLUDED_GARAGE_DOOR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_garage_door_EXPORTS
#define GARAGE_DOOR_API __GR_ATTR_EXPORT
#else
#define GARAGE_DOOR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_GARAGE_DOOR_API_H */
