/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft_channelizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(136d91ee4ea27e1203e77a71f54bdc1e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/fft_channelizer.h>
// pydoc.h is automatically generated in the build directory
#include <fft_channelizer_pydoc.h>

void bind_fft_channelizer(py::module& m)
{

    using fft_channelizer    = ::gr::iridium::fft_channelizer;


    py::class_<fft_channelizer, gr::sync_decimator,
        std::shared_ptr<fft_channelizer>>(m, "fft_channelizer", D(fft_channelizer))

        .def(py::init(&fft_channelizer::make),
           py::arg("fft_size"),
           py::arg("decimation"),
           py::arg("activate_streams"),
           py::arg("pdu_ports"),
           py::arg("max_burst_size"),
           py::arg("outstanding_limit"),
           py::arg("drop_overflow"),
           D(fft_channelizer,make)
        )
        




        
        .def("get_n_dropped_bursts",&fft_channelizer::get_n_dropped_bursts,       
            D(fft_channelizer,get_n_dropped_bursts)
        )


        
        .def("get_output_queue_size",&fft_channelizer::get_output_queue_size,       
            D(fft_channelizer,get_output_queue_size)
        )


        
        .def("get_output_max_queue_size",&fft_channelizer::get_output_max_queue_size,       
            D(fft_channelizer,get_output_max_queue_size)
        )

        ;




}








