/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iridium_frame_printer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cc076f2a982ac1007d74e8c3950dab45)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/iridium_frame_printer.h>
// pydoc.h is automatically generated in the build directory
#include <iridium_frame_printer_pydoc.h>

void bind_iridium_frame_printer(py::module& m)
{

    using iridium_frame_printer    = ::gr::iridium::iridium_frame_printer;


    py::class_<iridium_frame_printer, gr::block, gr::basic_block,
        std::shared_ptr<iridium_frame_printer>>(m, "iridium_frame_printer", D(iridium_frame_printer))

        .def(py::init(&iridium_frame_printer::make),
           py::arg("file_info"),
           D(iridium_frame_printer,make)
        )
        



        ;




}








