/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iuchar_to_complex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d2ee5f36427cd46c8d663462ffae73c3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/iuchar_to_complex.h>
// pydoc.h is automatically generated in the build directory
#include <iuchar_to_complex_pydoc.h>

void bind_iuchar_to_complex(py::module& m)
{

    using iuchar_to_complex    = ::gr::iridium::iuchar_to_complex;


    py::class_<iuchar_to_complex, gr::sync_decimator,
        std::shared_ptr<iuchar_to_complex>>(m, "iuchar_to_complex", D(iuchar_to_complex))

        .def(py::init(&iuchar_to_complex::make),
           D(iuchar_to_complex,make)
        )
        



        ;




}








