/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_null_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7f56a789b0d669d1d4b10f74e6a7db21)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/pdu_null_sink.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_null_sink_pydoc.h>

void bind_pdu_null_sink(py::module& m)
{

    using pdu_null_sink    = ::gr::iridium::pdu_null_sink;


    py::class_<pdu_null_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pdu_null_sink>>(m, "pdu_null_sink", D(pdu_null_sink))

        .def(py::init(&pdu_null_sink::make),
           D(pdu_null_sink,make)
        )
        



        ;




}








