/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tagged_burst_to_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d9633afe5e5d478e42ff48b6f1c00295)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/tagged_burst_to_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <tagged_burst_to_pdu_pydoc.h>

void bind_tagged_burst_to_pdu(py::module& m)
{

    using tagged_burst_to_pdu    = ::gr::iridium::tagged_burst_to_pdu;


    py::class_<tagged_burst_to_pdu, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tagged_burst_to_pdu>>(m, "tagged_burst_to_pdu", D(tagged_burst_to_pdu))

        .def(py::init(&tagged_burst_to_pdu::make),
           py::arg("max_burst_size"),
           py::arg("relative_center_frequency"),
           py::arg("relative_span"),
           py::arg("d_relative_sample_rate"),
           py::arg("sample_offset"),
           py::arg("outstanding_limit"),
           py::arg("drop_overflow"),
           D(tagged_burst_to_pdu,make)
        )
        




        
        .def("get_n_dropped_bursts",&tagged_burst_to_pdu::get_n_dropped_bursts,       
            D(tagged_burst_to_pdu,get_n_dropped_bursts)
        )


        
        .def("get_output_queue_size",&tagged_burst_to_pdu::get_output_queue_size,       
            D(tagged_burst_to_pdu,get_output_queue_size)
        )


        
        .def("get_output_max_queue_size",&tagged_burst_to_pdu::get_output_max_queue_size,       
            D(tagged_burst_to_pdu,get_output_max_queue_size)
        )

        ;




}








