schema_version: 1
detectors:
- action: timer
  detector_mode: scheduled
  detector_type: time
  hardware: USRP B2x0 - 30AD2E1
  parameters:
    timer_seconds: 10.0
  plugin: Mission-01
  runtime_parameters:
    timer_seconds: 10.0
    requester: autorun
    hardware_display_name: USRP B2x0 - 30AD2E1
    hardware_type: USRP B2x0
    hardware_uid: '0'
    hardware_uuid: '0'
    hardware_radio_name: USRP B210
    hardware_serial: 30AD2E1
    hardware_serial_argument: serial=30AD2E1
    hardware_interface: ''
    hardware_ip: ''
    hardware_daughterboard: ''
    serial: 30AD2E1
playlist:
- action: dummy_alert
  delay_seconds: 5.0
  interval_seconds: 60.0
  parameters:
    period_s: 20.0
    plot_pin: 'true'
    uid: dummy_alert
  plugin: Dummy
  repeat: false
