/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ainfosec
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_AINFOSEC_API_H
#define INCLUDED_AINFOSEC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ainfosec_EXPORTS
#define AINFOSEC_API __GR_ATTR_EXPORT
#else
#define AINFOSEC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_AINFOSEC_API_H */
