/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flow_control/burst_sdcch_subslot_splitter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7905eb32ad6a8f99c9f30389a805d137)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/flow_control/burst_sdcch_subslot_splitter.h>
// pydoc.h is automatically generated in the build directory
#include <burst_sdcch_subslot_splitter_pydoc.h>

void bind_burst_sdcch_subslot_splitter(py::module& m)
{

    using burst_sdcch_subslot_splitter    = ::gr::gsm::burst_sdcch_subslot_splitter;


    py::class_<burst_sdcch_subslot_splitter, gr::block, gr::basic_block,
        std::shared_ptr<burst_sdcch_subslot_splitter>>(m, "burst_sdcch_subslot_splitter", D(burst_sdcch_subslot_splitter))

        .def(py::init(&burst_sdcch_subslot_splitter::make),
           py::arg("mode"),
           D(burst_sdcch_subslot_splitter,make)
        )
        




        
        .def("get_mode",&burst_sdcch_subslot_splitter::get_mode,       
            D(burst_sdcch_subslot_splitter,get_mode)
        )


        
        .def("set_mode",&burst_sdcch_subslot_splitter::set_mode,       
            py::arg("mode"),
            D(burst_sdcch_subslot_splitter,set_mode)
        )

        ;

    py::enum_<::gr::gsm::splitter_mode>(m,"splitter_mode")
        .value("SPLITTER_SDCCH8", ::gr::gsm::splitter_mode::SPLITTER_SDCCH8) // 0
        .value("SPLITTER_SDCCH4", ::gr::gsm::splitter_mode::SPLITTER_SDCCH4) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::gsm::splitter_mode>();



}








