/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/bursts_printer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fb1cb7396a0f0e916397fcf689b88a5c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/bursts_printer.h>
// pydoc.h is automatically generated in the build directory
#include <bursts_printer_pydoc.h>

void bind_bursts_printer(py::module& m)
{

    using bursts_printer    = ::gr::gsm::bursts_printer;


    py::class_<bursts_printer, gr::block, gr::basic_block,
        std::shared_ptr<bursts_printer>>(m, "bursts_printer", D(bursts_printer))

        .def(py::init(&bursts_printer::make),
           py::arg("prepend_string"),
           py::arg("prepend_fnr") = false,
           py::arg("prepend_frame_count") = false,
           py::arg("print_payload_only") = false,
           py::arg("ignore_dummy_bursts") = false,
           D(bursts_printer,make)
        )
        



        ;




}








