/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/burst_file_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd4e1867e20966f4fea3d73f7453b912)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/burst_file_source.h>
// pydoc.h is automatically generated in the build directory
#include <burst_file_source_pydoc.h>

void bind_burst_file_source(py::module& m)
{

    using burst_file_source    = ::gr::gsm::burst_file_source;


    py::class_<burst_file_source, gr::block, gr::basic_block,
        std::shared_ptr<burst_file_source>>(m, "burst_file_source", D(burst_file_source))

        .def(py::init(&burst_file_source::make),
           py::arg("filename"),
           D(burst_file_source,make)
        )
        



        ;




}








