/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qa_utils/burst_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(896ecc99bec8f9b3e1aefde16b32c6dd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/qa_utils/burst_source.h>
// pydoc.h is automatically generated in the build directory
#include <burst_source_pydoc.h>

void bind_burst_source(py::module& m)
{

    using burst_source    = ::gr::gsm::burst_source;


    py::class_<burst_source, gr::block, gr::basic_block,
        std::shared_ptr<burst_source>>(m, "burst_source", D(burst_source))

        .def(py::init(&burst_source::make),
           py::arg("framenumbers"),
           py::arg("timeslots"),
           py::arg("burst_data"),
           D(burst_source,make)
        )
        




        
        .def("set_framenumbers",&burst_source::set_framenumbers,       
            py::arg("framenumbers"),
            D(burst_source,set_framenumbers)
        )


        
        .def("set_timeslots",&burst_source::set_timeslots,       
            py::arg("timeslots"),
            D(burst_source,set_timeslots)
        )


        
        .def("set_burst_data",&burst_source::set_burst_data,       
            py::arg("burst_data"),
            D(burst_source,set_burst_data)
        )


        
        .def("set_arfcn",&burst_source::set_arfcn,       
            py::arg("arfcn"),
            D(burst_source,set_arfcn)
        )

        ;




}








