/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flow_control/burst_fnr_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(60f07b587b57fcc919dc1612b577dc74)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/flow_control/burst_fnr_filter.h>
// pydoc.h is automatically generated in the build directory
#include <burst_fnr_filter_pydoc.h>

void bind_burst_fnr_filter(py::module& m)
{

    using burst_fnr_filter    = ::gr::gsm::burst_fnr_filter;


    py::class_<burst_fnr_filter, gr::block, gr::basic_block,
        std::shared_ptr<burst_fnr_filter>>(m, "burst_fnr_filter", D(burst_fnr_filter))

        .def(py::init(&burst_fnr_filter::make),
           py::arg("mode"),
           py::arg("fnr"),
           D(burst_fnr_filter,make)
        )
        




        
        .def("get_fn",&burst_fnr_filter::get_fn,       
            D(burst_fnr_filter,get_fn)
        )


        
        .def("set_fn",&burst_fnr_filter::set_fn,       
            py::arg("fn"),
            D(burst_fnr_filter,set_fn)
        )


        
        .def("get_mode",&burst_fnr_filter::get_mode,       
            D(burst_fnr_filter,get_mode)
        )


        
        .def("set_mode",&burst_fnr_filter::set_mode,       
            py::arg("mode"),
            D(burst_fnr_filter,set_mode)
        )


        
        .def("get_policy",&burst_fnr_filter::get_policy,       
            D(burst_fnr_filter,get_policy)
        )


        
        .def("set_policy",&burst_fnr_filter::set_policy,       
            py::arg("policy"),
            D(burst_fnr_filter,set_policy)
        )

        ;

    py::enum_<::gr::gsm::filter_mode>(m,"filter_mode")
        .value("FILTER_LESS_OR_EQUAL", ::gr::gsm::filter_mode::FILTER_LESS_OR_EQUAL) // 0
        .value("FILTER_GREATER_OR_EQUAL", ::gr::gsm::filter_mode::FILTER_GREATER_OR_EQUAL) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::gsm::filter_mode>();



}








