/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qa_utils/burst_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a4e452730d052832e8f9e37e641cd1a3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/qa_utils/burst_sink.h>
// pydoc.h is automatically generated in the build directory
#include <burst_sink_pydoc.h>

void bind_burst_sink(py::module& m)
{

    using burst_sink    = ::gr::gsm::burst_sink;


    py::class_<burst_sink, gr::block, gr::basic_block,
        std::shared_ptr<burst_sink>>(m, "burst_sink", D(burst_sink))

        .def(py::init(&burst_sink::make),
           D(burst_sink,make)
        )
        




        
        .def("get_framenumbers",&burst_sink::get_framenumbers,       
            D(burst_sink,get_framenumbers)
        )


        
        .def("get_timeslots",&burst_sink::get_timeslots,       
            D(burst_sink,get_timeslots)
        )


        
        .def("get_burst_data",&burst_sink::get_burst_data,       
            D(burst_sink,get_burst_data)
        )


        
        .def("get_bursts",&burst_sink::get_bursts,       
            D(burst_sink,get_bursts)
        )


        
        .def("get_sub_types",&burst_sink::get_sub_types,       
            D(burst_sink,get_sub_types)
        )


        
        .def("get_sub_slots",&burst_sink::get_sub_slots,       
            D(burst_sink,get_sub_slots)
        )

        ;




}








