/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flow_control/burst_type_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f0905cd262a0e1b2dce0281c770c972f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/flow_control/burst_type_filter.h>
// pydoc.h is automatically generated in the build directory
#include <burst_type_filter_pydoc.h>

void bind_burst_type_filter(py::module& m)
{

    using burst_type_filter    = ::gr::gsm::burst_type_filter;


    py::class_<burst_type_filter, gr::block, gr::basic_block,
        std::shared_ptr<burst_type_filter>>(m, "burst_type_filter", D(burst_type_filter))

        .def(py::init(&burst_type_filter::make),
           py::arg("selected_burst_types"),
           D(burst_type_filter,make)
        )
        




        
        .def("get_policy",&burst_type_filter::get_policy,       
            D(burst_type_filter,get_policy)
        )


        
        .def("set_policy",&burst_type_filter::set_policy,       
            py::arg("policy"),
            D(burst_type_filter,set_policy)
        )


        
        .def("set_selected_burst_types",&burst_type_filter::set_selected_burst_types,       
            py::arg("selected_burst_types"),
            D(burst_type_filter,set_selected_burst_types)
        )

        ;




}








