/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flow_control/burst_timeslot_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3dae8eb7200d8b209acf38768c33fcf6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/flow_control/burst_timeslot_filter.h>
// pydoc.h is automatically generated in the build directory
#include <burst_timeslot_filter_pydoc.h>

void bind_burst_timeslot_filter(py::module& m)
{

    using burst_timeslot_filter    = ::gr::gsm::burst_timeslot_filter;


    py::class_<burst_timeslot_filter, gr::block, gr::basic_block,
        std::shared_ptr<burst_timeslot_filter>>(m, "burst_timeslot_filter", D(burst_timeslot_filter))

        .def(py::init(&burst_timeslot_filter::make),
           py::arg("timeslot"),
           D(burst_timeslot_filter,make)
        )
        




        
        .def("get_tn",&burst_timeslot_filter::get_tn,       
            D(burst_timeslot_filter,get_tn)
        )


        
        .def("set_tn",&burst_timeslot_filter::set_tn,       
            py::arg("tn"),
            D(burst_timeslot_filter,set_tn)
        )


        
        .def("get_policy",&burst_timeslot_filter::get_policy,       
            D(burst_timeslot_filter,get_policy)
        )


        
        .def("set_policy",&burst_timeslot_filter::set_policy,       
            py::arg("policy"),
            D(burst_timeslot_filter,set_policy)
        )

        ;




}








