/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decoding/control_channels_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(27ccac5f7443c012950a9cedefae17d5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/decoding/control_channels_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <control_channels_decoder_pydoc.h>

void bind_control_channels_decoder(py::module& m)
{

    using control_channels_decoder    = ::gr::gsm::control_channels_decoder;


    py::class_<control_channels_decoder, gr::block, gr::basic_block,
        std::shared_ptr<control_channels_decoder>>(m, "control_channels_decoder", D(control_channels_decoder))

        .def(py::init(&control_channels_decoder::make),
           D(control_channels_decoder,make)
        )
        



        ;




}








