/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flow_control/dummy_burst_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(039530bfc8c2ac0e4a0ddb1e66312d1a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/flow_control/dummy_burst_filter.h>
// pydoc.h is automatically generated in the build directory
#include <dummy_burst_filter_pydoc.h>

void bind_dummy_burst_filter(py::module& m)
{

    using dummy_burst_filter    = ::gr::gsm::dummy_burst_filter;


    py::class_<dummy_burst_filter, gr::block, gr::basic_block,
        std::shared_ptr<dummy_burst_filter>>(m, "dummy_burst_filter", D(dummy_burst_filter))

        .def(py::init(&dummy_burst_filter::make),
           D(dummy_burst_filter,make)
        )
        




        
        .def("get_policy",&dummy_burst_filter::get_policy,       
            D(dummy_burst_filter,get_policy)
        )


        
        .def("set_policy",&dummy_burst_filter::set_policy,       
            py::arg("policy"),
            D(dummy_burst_filter,set_policy)
        )

        ;




}








