/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/extract_cmc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73e93de535eebe422139618f75645fa0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/extract_cmc.h>
// pydoc.h is automatically generated in the build directory
#include <extract_cmc_pydoc.h>

void bind_extract_cmc(py::module& m)
{

    using extract_cmc    = ::gr::gsm::extract_cmc;


    py::class_<extract_cmc, gr::block, gr::basic_block,
        std::shared_ptr<extract_cmc>>(m, "extract_cmc", D(extract_cmc))

        .def(py::init(&extract_cmc::make),
           D(extract_cmc,make)
        )
        




        
        .def("get_framenumbers",&extract_cmc::get_framenumbers,       
            D(extract_cmc,get_framenumbers)
        )


        
        .def("get_a5_versions",&extract_cmc::get_a5_versions,       
            D(extract_cmc,get_a5_versions)
        )


        
        .def("get_start_ciphering",&extract_cmc::get_start_ciphering,       
            D(extract_cmc,get_start_ciphering)
        )

        ;




}








