/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/fn_time.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff956c9730003ca3a43efca36f5dd5ee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/fn_time.h>
// pydoc.h is automatically generated in the build directory
#include <fn_time_pydoc.h>

void bind_fn_time(py::module& m)
{




        m.def("fn_time_delta_cpp",&::gr::gsm::fn_time_delta_cpp,
            py::arg("fn_ref"),
            py::arg("time_ref"),
            py::arg("fn_x"),
            py::arg("time_hint"),
            py::arg("ts_num"),
            py::arg("ts_ref"),
            D(fn_time_delta_cpp)
        );



}








