/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmitter/gen_test_ab.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(82aebc8c24cd875106a35da63861202e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/transmitter/gen_test_ab.h>
// pydoc.h is automatically generated in the build directory
#include <gen_test_ab_pydoc.h>

void bind_gen_test_ab(py::module& m)
{

    using gen_test_ab    = ::gr::gsm::gen_test_ab;


    py::class_<gen_test_ab, gr::block, gr::basic_block,
        std::shared_ptr<gen_test_ab>>(m, "gen_test_ab", D(gen_test_ab))

        .def(py::init(&gen_test_ab::make),
           D(gen_test_ab,make)
        )
        



        ;




}








