/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/message_printer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0e75d88f5c33cd261fe1e4ab6d33fd35)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/message_printer.h>
// pydoc.h is automatically generated in the build directory
#include <message_printer_pydoc.h>

void bind_message_printer(py::module& m)
{

    using message_printer    = ::gr::gsm::message_printer;


    py::class_<message_printer, gr::block, gr::basic_block,
        std::shared_ptr<message_printer>>(m, "message_printer", D(message_printer))

        .def(py::init(&message_printer::make),
           py::arg("prepend_string"),
           py::arg("prepend_fnr") = false,
           py::arg("prepend_frame_count") = false,
           py::arg("print_gsmtap_header") = false,
           D(message_printer,make)
        )
        



        ;




}








