/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmitter/preprocess_tx_burst.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d2a70edb7b7bb2eb3b53546ac0ce16d6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/transmitter/preprocess_tx_burst.h>
// pydoc.h is automatically generated in the build directory
#include <preprocess_tx_burst_pydoc.h>

void bind_preprocess_tx_burst(py::module& m)
{

    using preprocess_tx_burst    = ::gr::gsm::preprocess_tx_burst;


    py::class_<preprocess_tx_burst, gr::block, gr::basic_block,
        std::shared_ptr<preprocess_tx_burst>>(m, "preprocess_tx_burst", D(preprocess_tx_burst))

        .def(py::init(&preprocess_tx_burst::make),
           D(preprocess_tx_burst,make)
        )
        



        ;




}








