/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demapping/tch_f_chans_demapper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d35ba78e4aa7fb7f34c0ec18a60875f0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/demapping/tch_f_chans_demapper.h>
// pydoc.h is automatically generated in the build directory
#include <tch_f_chans_demapper_pydoc.h>

void bind_tch_f_chans_demapper(py::module& m)
{

    using tch_f_chans_demapper    = ::gr::gsm::tch_f_chans_demapper;


    py::class_<tch_f_chans_demapper, gr::block, gr::basic_block,
        std::shared_ptr<tch_f_chans_demapper>>(m, "tch_f_chans_demapper", D(tch_f_chans_demapper))

        .def(py::init(&tch_f_chans_demapper::make),
           py::arg("timeslot_nr"),
           D(tch_f_chans_demapper,make)
        )
        



        ;




}








