/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(trx/trx_burst_if.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b7193e067e3d9cba3d3f45076f5adef8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/trx/trx_burst_if.h>
// pydoc.h is automatically generated in the build directory
#include <trx_burst_if_pydoc.h>

void bind_trx_burst_if(py::module& m)
{

    using trx_burst_if    = ::gr::gsm::trx_burst_if;


    py::class_<trx_burst_if, gr::block, gr::basic_block,
        std::shared_ptr<trx_burst_if>>(m, "trx_burst_if", D(trx_burst_if))

        .def(py::init(&trx_burst_if::make),
           py::arg("bind_addr"),
           py::arg("remote_addr"),
           py::arg("base_port"),
           D(trx_burst_if,make)
        )
        



        ;




}








