/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmitter/txtime_setter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bb9e7d69e0565251e3c044257b6ea889)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/transmitter/txtime_setter.h>
// pydoc.h is automatically generated in the build directory
#include <txtime_setter_pydoc.h>

void bind_txtime_setter(py::module& m)
{

    using txtime_setter    = ::gr::gsm::txtime_setter;


    py::class_<txtime_setter, gr::block, gr::basic_block,
        std::shared_ptr<txtime_setter>>(m, "txtime_setter", D(txtime_setter))

        .def(py::init(&txtime_setter::make),
           py::arg("init_fn"),
           py::arg("init_time_secs"),
           py::arg("init_time_fracs"),
           py::arg("time_hint_secs"),
           py::arg("time_hint_fracs"),
           py::arg("timing_advance"),
           py::arg("delay_correction"),
           D(txtime_setter,make)
        )
        




        
        .def("set_fn_time_reference",&txtime_setter::set_fn_time_reference,       
            py::arg("fn"),
            py::arg("ts"),
            py::arg("time_secs"),
            py::arg("time_fracs"),
            D(txtime_setter,set_fn_time_reference)
        )


        
        .def("set_time_hint",&txtime_setter::set_time_hint,       
            py::arg("time_hint_secs"),
            py::arg("time_hint_fracs"),
            D(txtime_setter,set_time_hint)
        )


        
        .def("set_delay_correction",&txtime_setter::set_delay_correction,       
            py::arg("delay_correction"),
            D(txtime_setter,set_delay_correction)
        )


        
        .def("set_timing_advance",&txtime_setter::set_timing_advance,       
            py::arg("timing_advance"),
            D(txtime_setter,set_timing_advance)
        )

        ;




}








