/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(misc_utils/udp_socket.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(78de1eb875aeaaf710c427cd138f3ee1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gsm/misc_utils/udp_socket.h>
// pydoc.h is automatically generated in the build directory
#include <udp_socket_pydoc.h>

void bind_udp_socket(py::module& m)
{

    using udp_socket    = ::gr::gsm::udp_socket;


    py::class_<udp_socket,
        std::shared_ptr<udp_socket>>(m, "udp_socket", D(udp_socket))

        .def(py::init<std::string const &,std::string const &,std::string const &,std::string const &,size_t>(),           py::arg("bind_addr"),
           py::arg("src_port"),
           py::arg("remote_addr"),
           py::arg("dst_port"),
           py::arg("mtu"),
           D(udp_socket,udp_socket)
        )


        
        .def("udp_send",&udp_socket::udp_send,       
            py::arg("data"),
            py::arg("len"),
            D(udp_socket,udp_send)
        )

        ;




}








