/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(access_code_removal_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8c5350c088bc9ea63f67462618b35d53)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/access_code_removal_b.h>
// pydoc.h is automatically generated in the build directory
#include <access_code_removal_b_pydoc.h>

void bind_access_code_removal_b(py::module& m)
{

    using access_code_removal_b    = ::gr::ieee802_15_4::access_code_removal_b;


    py::class_<access_code_removal_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<access_code_removal_b>>(m, "access_code_removal_b", D(access_code_removal_b))

        .def(py::init(&access_code_removal_b::make),
           py::arg("len_payload"),
           D(access_code_removal_b,make)
        )
        



        ;




}








