/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(codeword_demapper_ib.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a17fb1b6f4a550f76c7efcdc64da823d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/codeword_demapper_ib.h>
// pydoc.h is automatically generated in the build directory
#include <codeword_demapper_ib_pydoc.h>

void bind_codeword_demapper_ib(py::module& m)
{

    using codeword_demapper_ib    = ::gr::ieee802_15_4::codeword_demapper_ib;


    py::class_<codeword_demapper_ib, gr::block, gr::basic_block,
        std::shared_ptr<codeword_demapper_ib>>(m, "codeword_demapper_ib", D(codeword_demapper_ib))

        .def(py::init(&codeword_demapper_ib::make),
           py::arg("bits_per_cw"),
           py::arg("codewords"),
           D(codeword_demapper_ib,make)
        )
        



        ;




}








