/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(codeword_mapper_bi.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ae23614c6694004781086d4d60e8de47)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/codeword_mapper_bi.h>
// pydoc.h is automatically generated in the build directory
#include <codeword_mapper_bi_pydoc.h>

void bind_codeword_mapper_bi(py::module& m)
{

    using codeword_mapper_bi    = ::gr::ieee802_15_4::codeword_mapper_bi;


    py::class_<codeword_mapper_bi, gr::block, gr::basic_block,
        std::shared_ptr<codeword_mapper_bi>>(m, "codeword_mapper_bi", D(codeword_mapper_bi))

        .def(py::init(&codeword_mapper_bi::make),
           py::arg("bits_per_cw"),
           py::arg("codewords"),
           D(codeword_mapper_bi,make)
        )
        



        ;




}








