/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(deinterleaver_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(519e9f59bfbe71d8933e563ac5f2cf1c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/deinterleaver_ff.h>
// pydoc.h is automatically generated in the build directory
#include <deinterleaver_ff_pydoc.h>

void bind_deinterleaver_ff(py::module& m)
{

    using deinterleaver_ff    = ::gr::ieee802_15_4::deinterleaver_ff;


    py::class_<deinterleaver_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<deinterleaver_ff>>(m, "deinterleaver_ff", D(deinterleaver_ff))

        .def(py::init(&deinterleaver_ff::make),
           py::arg("intlv_seq"),
           D(deinterleaver_ff,make)
        )
        



        ;




}








