/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dqcsk_demapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d50c0b368f7887882c54435946de81b9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/dqcsk_demapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <dqcsk_demapper_cc_pydoc.h>

void bind_dqcsk_demapper_cc(py::module& m)
{

    using dqcsk_demapper_cc    = ::gr::ieee802_15_4::dqcsk_demapper_cc;


    py::class_<dqcsk_demapper_cc, gr::block, gr::basic_block,
        std::shared_ptr<dqcsk_demapper_cc>>(m, "dqcsk_demapper_cc", D(dqcsk_demapper_cc))

        .def(py::init(&dqcsk_demapper_cc::make),
           py::arg("chirp_seq"),
           py::arg("time_gap_1"),
           py::arg("time_gap_2"),
           py::arg("len_subchirp"),
           py::arg("num_subchirps"),
           D(dqcsk_demapper_cc,make)
        )
        



        ;




}








