/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dqpsk_soft_demapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e485594ab71bc15aa9bb6ff996f6a492)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/dqpsk_soft_demapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <dqpsk_soft_demapper_cc_pydoc.h>

void bind_dqpsk_soft_demapper_cc(py::module& m)
{

    using dqpsk_soft_demapper_cc    = ::gr::ieee802_15_4::dqpsk_soft_demapper_cc;


    py::class_<dqpsk_soft_demapper_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dqpsk_soft_demapper_cc>>(m, "dqpsk_soft_demapper_cc", D(dqpsk_soft_demapper_cc))

        .def(py::init(&dqpsk_soft_demapper_cc::make),
           py::arg("framelen"),
           D(dqpsk_soft_demapper_cc,make)
        )
        



        ;




}








