/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(interleaver_ii.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c4326cb66b7b1f42fd16727df3cebf8e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/interleaver_ii.h>
// pydoc.h is automatically generated in the build directory
#include <interleaver_ii_pydoc.h>

void bind_interleaver_ii(py::module& m)
{

    using interleaver_ii    = ::gr::ieee802_15_4::interleaver_ii;


    py::class_<interleaver_ii, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<interleaver_ii>>(m, "interleaver_ii", D(interleaver_ii))

        .def(py::init(&interleaver_ii::make),
           py::arg("intlv_seq"),
           py::arg("forward"),
           D(interleaver_ii,make)
        )
        



        ;




}








