/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4583c6d0d4450f5e49034ceb50f271a5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/packet_sink.h>
// pydoc.h is automatically generated in the build directory
#include <packet_sink_pydoc.h>

void bind_packet_sink(py::module& m)
{

    using packet_sink    = ::gr::ieee802_15_4::packet_sink;


    py::class_<packet_sink, gr::block, gr::basic_block,
        std::shared_ptr<packet_sink>>(m, "packet_sink", D(packet_sink))

        .def(py::init(&packet_sink::make),
           py::arg("threshold") = 10,
           D(packet_sink,make)
        )
        



        ;




}








