/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phr_removal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1beb9fa3bff89cce86e21837cc441add)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/phr_removal.h>
// pydoc.h is automatically generated in the build directory
#include <phr_removal_pydoc.h>

void bind_phr_removal(py::module& m)
{

    using phr_removal    = ::gr::ieee802_15_4::phr_removal;


    py::class_<phr_removal, gr::block, gr::basic_block,
        std::shared_ptr<phr_removal>>(m, "phr_removal", D(phr_removal))

        .def(py::init(&phr_removal::make),
           py::arg("phr"),
           D(phr_removal,make)
        )
        



        ;




}








