/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phr_prefixer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6cb39ce891f1fac9dd876bff7bc49ae3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/phr_prefixer.h>
// pydoc.h is automatically generated in the build directory
#include <phr_prefixer_pydoc.h>

void bind_phr_prefixer(py::module& m)
{

    using phr_prefixer    = ::gr::ieee802_15_4::phr_prefixer;


    py::class_<phr_prefixer, gr::block, gr::basic_block,
        std::shared_ptr<phr_prefixer>>(m, "phr_prefixer", D(phr_prefixer))

        .def(py::init(&phr_prefixer::make),
           py::arg("phr"),
           D(phr_prefixer,make)
        )
        



        ;




}








