/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble_tagger_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f40c949e08ffd3856e17349c7f834615)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/preamble_tagger_cc.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_tagger_cc_pydoc.h>

void bind_preamble_tagger_cc(py::module& m)
{

    using preamble_tagger_cc    = ::gr::ieee802_15_4::preamble_tagger_cc;


    py::class_<preamble_tagger_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<preamble_tagger_cc>>(m, "preamble_tagger_cc", D(preamble_tagger_cc))

        .def(py::init(&preamble_tagger_cc::make),
           py::arg("len_preamble"),
           D(preamble_tagger_cc,make)
        )
        



        ;




}








