/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble_sfd_prefixer_ii.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bbee31d1c7d1296b74bd326d5e90a736)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/preamble_sfd_prefixer_ii.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_sfd_prefixer_ii_pydoc.h>

void bind_preamble_sfd_prefixer_ii(py::module& m)
{

    using preamble_sfd_prefixer_ii    = ::gr::ieee802_15_4::preamble_sfd_prefixer_ii;


    py::class_<preamble_sfd_prefixer_ii, gr::block, gr::basic_block,
        std::shared_ptr<preamble_sfd_prefixer_ii>>(m, "preamble_sfd_prefixer_ii", D(preamble_sfd_prefixer_ii))

        .def(py::init(&preamble_sfd_prefixer_ii::make),
           py::arg("preamble"),
           py::arg("sfd"),
           py::arg("nsym_frame"),
           D(preamble_sfd_prefixer_ii,make)
        )
        



        ;




}








