/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qpsk_mapper_if.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fd92e244e3b58d68467e6c8c5d2f8212)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/qpsk_mapper_if.h>
// pydoc.h is automatically generated in the build directory
#include <qpsk_mapper_if_pydoc.h>

void bind_qpsk_mapper_if(py::module& m)
{

    using qpsk_mapper_if    = ::gr::ieee802_15_4::qpsk_mapper_if;


    py::class_<qpsk_mapper_if, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<qpsk_mapper_if>>(m, "qpsk_mapper_if", D(qpsk_mapper_if))

        .def(py::init(&qpsk_mapper_if::make),
           D(qpsk_mapper_if,make)
        )
        



        ;




}








