/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rime_stack.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1ece006b2fd03e3e85a850496450bd50)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/rime_stack.h>
// pydoc.h is automatically generated in the build directory
#include <rime_stack_pydoc.h>

void bind_rime_stack(py::module& m)
{

    using rime_stack    = ::gr::ieee802_15_4::rime_stack;


    py::class_<rime_stack, gr::block, gr::basic_block,
        std::shared_ptr<rime_stack>>(m, "rime_stack", D(rime_stack))

        .def(py::init(&rime_stack::make),
           py::arg("bc_channels"),
           py::arg("uc_channels"),
           py::arg("ruc_channels"),
           py::arg("rime_add"),
           D(rime_stack,make)
        )
        



        ;




}








