/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zeropadding_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2751676ae2b54f7d927ecb3f4ef9bfc6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_15_4/zeropadding_b.h>
// pydoc.h is automatically generated in the build directory
#include <zeropadding_b_pydoc.h>

void bind_zeropadding_b(py::module& m)
{

    using zeropadding_b    = ::gr::ieee802_15_4::zeropadding_b;


    py::class_<zeropadding_b, gr::block, gr::basic_block,
        std::shared_ptr<zeropadding_b>>(m, "zeropadding_b", D(zeropadding_b))

        .def(py::init(&zeropadding_b::make),
           py::arg("nzeros"),
           D(zeropadding_b,make)
        )
        



        ;




}








