/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ask_env.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0021df37e7e929403d8392c5b9899e76)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tpms/ask_env.h>
// pydoc.h is automatically generated in the build directory
#include <ask_env_pydoc.h>

void bind_ask_env(py::module& m)
{

    using ask_env    = ::gr::tpms::ask_env;


    py::class_<ask_env, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ask_env>>(m, "ask_env", D(ask_env))

        .def(py::init(&ask_env::make),
           py::arg("alpha"),
           D(ask_env,make)
        )
        




        
        .def("set_alpha",&ask_env::set_alpha,       
            py::arg("var"),
            D(ask_env,set_alpha)
        )


        
        .def("alpha",&ask_env::alpha,       
            D(ask_env,alpha)
        )

        ;




}








