/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(burst_detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2c342e87368b0162483eb8e296c9a488)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tpms/burst_detector.h>
// pydoc.h is automatically generated in the build directory
#include <burst_detector_pydoc.h>

void bind_burst_detector(py::module& m)
{

    using burst_detector    = ::gr::tpms::burst_detector;


    py::class_<burst_detector, gr::block, gr::basic_block,
        std::shared_ptr<burst_detector>>(m, "burst_detector", D(burst_detector))

        .def(py::init(&burst_detector::make),
           D(burst_detector,make)
        )
        



        ;




}








