/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(14db17840cdbd66a1bb342c22e25c019)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dect2/packet_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <packet_decoder_pydoc.h>

void bind_packet_decoder(py::module& m)
{

    using packet_decoder    = ::gr::dect2::packet_decoder;


    py::class_<packet_decoder, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<packet_decoder>>(m, "packet_decoder", D(packet_decoder))

        .def(py::init(&packet_decoder::make),
           D(packet_decoder,make)
        )
        




        
        .def("select_rx_part",&packet_decoder::select_rx_part,       
            py::arg("rx_id"),
            D(packet_decoder,select_rx_part)
        )

        ;




}








