/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phase_diff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6002789bbe9c91eb7f843ba82b82720b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dect2/phase_diff.h>
// pydoc.h is automatically generated in the build directory
#include <phase_diff_pydoc.h>

void bind_phase_diff(py::module& m)
{

    using phase_diff    = ::gr::dect2::phase_diff;


    py::class_<phase_diff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<phase_diff>>(m, "phase_diff", D(phase_diff))

        .def(py::init(&phase_diff::make),
           D(phase_diff,make)
        )
        



        ;




}








